{% set version = "2024b" %}

package:
  name: tzcode
  version: {{ version }}

source:
  url: https://data.iana.org/time-zones/releases/tzdb-{{ version }}.tar.lz
  sha256: 22674a67786d3ec1b0547305904011cb2b9126166e72abbbea39425de5595233

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - lzip
    - make
  host:
  run:

test:
  commands:
    - tzselect --help
    - zdump --help
    - zic --help
    # make sure we didn't install the data
    - test ! -f "${PREFIX}/share/zoneinfo"

about:
  home: https://www.iana.org/time-zones
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The Time Zone Database (often called tz or zoneinfo) code
  description: |
    The Time Zone Database (often called tz or zoneinfo) contains
    code (this package) and data (the tzdata package) that represent the
    history of local time for many
    representative locations around the globe. It is updated periodically
    to reflect changes made by political bodies to time zone boundaries,
    UTC offsets, and daylight-saving rules.
  doc_url: https://tools.ietf.org/html/rfc6557

extra:
  recipe-maintainers:
    - sodre
    - ocefpaf
    - xylar
