schema_version: 1

context:
  version: 2026a

package:
  name: tzcode
  version: ${{ version }}

source:
  url: https://data.iana.org/time-zones/releases/tzcode${{ version }}.tar.gz
  sha256: f80a17a2eddd2b54041f9c98d75b0aa8038b016d7c5de72892a146d9938740e1

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - make
  host:
  run:

tests:
  - script:
      - tzselect --help
      - zdump --help
      - zic --help
      - test ! -f "${PREFIX}/share/zoneinfo"

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: The Time Zone Database (often called tz or zoneinfo) code
  description: |
    The Time Zone Database (often called tz or zoneinfo) contains
    code (this package) and data (the tzdata package) that represent the
    history of local time for many
    representative locations around the globe. It is updated periodically
    to reflect changes made by political bodies to time zone boundaries,
    UTC offsets, and daylight-saving rules.
  homepage: https://www.iana.org/time-zones
  documentation: https://tools.ietf.org/html/rfc6557

extra:
  recipe-maintainers:
    - sodre
    - ocefpaf
    - xylar
