schema_version: 1

context:
  version: "2026c"

package:
  name: tzcode
  version: ${{ version }}

source:
  - url: https://data.iana.org/time-zones/releases/tzcode${{ version }}.tar.gz
    sha256: b1cffc3ace4c4c7cd0efba2f7add86ec3d0b79da48bcf03582671fd3c8feace8
  - url: https://data.iana.org/time-zones/releases/tzdata${{ version }}.tar.gz
    sha256: e4a178a4477f3d0ea77cc31828ff72aa38feff8d61aa13e7e99e142e9d902be4
    target_directory: tzdata

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - make
  host:
  run:

tests:
  - script:
      - tzselect --help
      - zdump --help
      - zic --help
      - test ! -d "${PREFIX}/man"
      - test ! -f "${PREFIX}/share/zoneinfo"

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: The Time Zone Database (often called tz or zoneinfo) code
  description: |
    The Time Zone Database (often called tz or zoneinfo) contains
    code (this package) and data (the tzdata package) that represent the
    history of local time for many
    representative locations around the globe. It is updated periodically
    to reflect changes made by political bodies to time zone boundaries,
    UTC offsets, and daylight-saving rules.
  homepage: https://www.iana.org/time-zones
  documentation: https://tools.ietf.org/html/rfc6557

extra:
  recipe-maintainers:
    - sodre
    - ocefpaf
    - xylar
